In [1]:
import sklearn
print(sklearn.__version__)

1.4.1.post1

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_squared_error, r2_score
import joblib
import pyodbc

In [3]:
import pyodbc
print(pyodbc.drivers())

['SQL Server', 'ODBC Driver 18 for SQL Server']

In [4]:
# Connect to Azure SQL
conn = pyodbc.connect(
    "DRIVER={ODBC Driver 18 for SQL Server};"
    "SERVER=cloudsqlserver44.database.windows.net;DATABASE=cloudsql44;"
    "UID=sqladmin;PWD=Group_44"
)

# Fetch transformed data
query = "SELECT * FROM TransformedData"
df = pd.read_sql(query, conn)

C:\Users\HP\AppData\Local\Temp\ipykernel_17816\1065484968.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

In [5]:
df.head()

,Hshd_num,Basket_num,Purchase_Date,Product_num,Department,Commodity,Spend,Units,Store_region,Week_num,Year,Loyalty_flag,Age_range,Marital_status,Income_range,Homeowner_desc,Hshd_composition,Hshd_size,Children
0,577,2,2018-08-17,83652,PHARMA,MEDICATION,0.59,1,CENTRAL,32,2018,Y,65-74,Married,UNDER 35K,Homeowner,2 Adults,2.00,1.24
1,1916,9,2018-08-17,6157725,FOOD,GROCERY STAPLE,3.49,1,WEST,32,2018,N,55-64,Single,35-49K,Homeowner,Single Female,1.00,1.24
2,514,16,2018-08-17,654479,FOOD,GROCERY STAPLE,2.24,1,CENTRAL,32,2018,Y,65-74,Married,75-99K,Homeowner,2 Adults and Kids,2.14,1.24
3,514,16,2018-08-17,8118,FOOD,PRODUCE,5.39,1,CENTRAL,32,2018,Y,65-74,Married,75-99K,Homeowner,2 Adults and Kids,2.14,1.24
4,361,25,2018-08-17,94343,NON-FOOD,PERSONAL CARE,1.00,1,SOUTH,32,2018,N,55-64,Married,100-150K,Homeowner,2 Adults and Kids,3.00,1.00

In [6]:
# Define a function to calculate average income in full value
def transform_income_range(value):
    try:
        if "UNDER" in value:
            # Extract the numeric part and calculate mid-point for "UNDER 35K"
            return (int(value.split()[1].replace("K", "")) / 2) * 1000
        elif "150K+" in value:
            return 150 * 1000  # Assume 150,000 for "150K+"
        elif "-" in value:
            # Extract the numeric parts, remove "K", and calculate average
            lower, upper = map(lambda x: int(x.replace("K", "")), value.split('-'))
            return ((lower + upper) / 2) * 1000
        elif value == "Unknown":
            return 0  # Assign 0 for Unknown
        else:
            return None
    except Exception as e:
        print(f"Error processing value: {value}, Error: {e}")
        return None

# Apply the transformation function to the Income_range column
df["Income_range"] = df["Income_range"].apply(transform_income_range)

In [7]:
df['CLV'] = df.groupby('Hshd_num')['Spend'].transform('sum') / df.groupby('Hshd_num')['Basket_num'].transform('count')
df.head()

,Hshd_num,Basket_num,Purchase_Date,Product_num,Department,Commodity,Spend,Units,Store_region,Week_num,Year,Loyalty_flag,Age_range,Marital_status,Income_range,Homeowner_desc,Hshd_composition,Hshd_size,Children,CLV
0,577,2,2018-08-17,83652,PHARMA,MEDICATION,0.59,1,CENTRAL,32,2018,Y,65-74,Married,17500.0,Homeowner,2 Adults,2.00,1.24,3.844048
1,1916,9,2018-08-17,6157725,FOOD,GROCERY STAPLE,3.49,1,WEST,32,2018,N,55-64,Single,42000.0,Homeowner,Single Female,1.00,1.24,3.336231
2,514,16,2018-08-17,654479,FOOD,GROCERY STAPLE,2.24,1,CENTRAL,32,2018,Y,65-74,Married,87000.0,Homeowner,2 Adults and Kids,2.14,1.24,4.377158
3,514,16,2018-08-17,8118,FOOD,PRODUCE,5.39,1,CENTRAL,32,2018,Y,65-74,Married,87000.0,Homeowner,2 Adults and Kids,2.14,1.24,4.377158
4,361,25,2018-08-17,94343,NON-FOOD,PERSONAL CARE,1.00,1,SOUTH,32,2018,N,55-64,Married,125000.0,Homeowner,2 Adults and Kids,3.00,1.00,3.990072

In [8]:
# Display the updated DataFrame
df.head()

,Hshd_num,Basket_num,Purchase_Date,Product_num,Department,Commodity,Spend,Units,Store_region,Week_num,Year,Loyalty_flag,Age_range,Marital_status,Income_range,Homeowner_desc,Hshd_composition,Hshd_size,Children,CLV
0,577,2,2018-08-17,83652,PHARMA,MEDICATION,0.59,1,CENTRAL,32,2018,Y,65-74,Married,17500.0,Homeowner,2 Adults,2.00,1.24,3.844048
1,1916,9,2018-08-17,6157725,FOOD,GROCERY STAPLE,3.49,1,WEST,32,2018,N,55-64,Single,42000.0,Homeowner,Single Female,1.00,1.24,3.336231
2,514,16,2018-08-17,654479,FOOD,GROCERY STAPLE,2.24,1,CENTRAL,32,2018,Y,65-74,Married,87000.0,Homeowner,2 Adults and Kids,2.14,1.24,4.377158
3,514,16,2018-08-17,8118,FOOD,PRODUCE,5.39,1,CENTRAL,32,2018,Y,65-74,Married,87000.0,Homeowner,2 Adults and Kids,2.14,1.24,4.377158
4,361,25,2018-08-17,94343,NON-FOOD,PERSONAL CARE,1.00,1,SOUTH,32,2018,N,55-64,Married,125000.0,Homeowner,2 Adults and Kids,3.00,1.00,3.990072

In [9]:
# Feature selection
X = df[['Spend', 'Units', 'Income_range', 'Hshd_size', 'Children']]
y = df['CLV']  # Target: Customer Lifetime Value

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train the Gradient Boosting model
model_clv = GradientBoostingRegressor()
model_clv.fit(X_train, y_train)

# Evaluate the model
y_pred = model_clv.predict(X_test)
print("CLV Prediction R2 Score:", r2_score(y_test, y_pred))
print("CLV Prediction MSE:", mean_squared_error(y_test, y_pred))

# Save the model
joblib.dump(model_clv, "gradient_boosting_clv.pkl")

CLV Prediction R2 Score: 0.25551513270988446
CLV Prediction MSE: 0.5131383751720974

['gradient_boosting_clv.pkl']

In [10]:
# Step 1: Commodity Frequency
commodity_frequency = df['Commodity'].value_counts()

# Step 2: Identify Top Commodities by Frequency
top_commodities_by_frequency = commodity_frequency.nlargest(5).index.tolist()

# Step 3: Analyze Revenue Contribution
commodity_revenue = df.groupby('Commodity')['Spend'].sum().sort_values(ascending=False)

# Step 4: Identify Top Commodities by Revenue
top_commodities_by_revenue = commodity_revenue.nlargest(5).index.tolist()

# Step 5: Combine Results
# Use union of both top frequency and revenue commodities to get a robust selection
selected_commodities = list(set(top_commodities_by_frequency + top_commodities_by_revenue))

# Display Results
print("Selected Commodities for Basket Analysis:")
print(f"Top Commodities by Frequency: {top_commodities_by_frequency}")
print(f"Top Commodities by Revenue: {top_commodities_by_revenue}")
print(f"Final Selected Commodities: {selected_commodities}")

Selected Commodities for Basket Analysis:
Top Commodities by Frequency: ['GROCERY STAPLE            ', 'PRODUCE                   ', 'DAIRY                     ', 'FROZEN FOOD               ', 'BEVERAGE - NON WATER      ']
Top Commodities by Revenue: ['GROCERY STAPLE            ', 'PRODUCE                   ', 'FROZEN FOOD               ', 'DAIRY                     ', 'HOUSEHOLD                 ']
Final Selected Commodities: ['DAIRY                     ', 'GROCERY STAPLE            ', 'BEVERAGE - NON WATER      ', 'PRODUCE                   ', 'FROZEN FOOD               ', 'HOUSEHOLD                 ']

In [11]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder

# Labeling Commodities
# Create a target column 'BasketLabel' for selected commodities
selected_commodities = ['FROZEN FOOD', 'GROCERY STAPLE', 'DAIRY', 'BEVERAGE - NON WATER', 'PRODUCE', 'HOUSEHOLD']
df['BasketLabel'] = df['Commodity'].apply(lambda x: 1 if x in selected_commodities else 0)

# Feature Engineering
# Select features for prediction
features = ['Spend', 'Units', 'Hshd_size', 'Children', 'Income_range', 'Store_region']

# Encode categorical features
encoder = LabelEncoder()
df['Store_region_encoded'] = encoder.fit_transform(df['Store_region'])

# Prepare feature matrix and target vector
X = df[['Spend', 'Units', 'Hshd_size', 'Children', 'Income_range', 'Store_region_encoded']]
y = df['BasketLabel']

# Step 4: Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 5: Train Random Forest Model
model_basket = RandomForestClassifier(n_estimators=100, random_state=42)
model_basket.fit(X_train, y_train)

# Step 6: Evaluate the Model
y_pred = model_basket.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Basket Analysis Accuracy: {accuracy:.2f}")

# Step 7: Save the Model
joblib.dump(model_basket, "random_forest_basket.pkl")
print("Model saved as 'random_forest_basket.pkl'")

Basket Analysis Accuracy: 1.00
Model saved as 'random_forest_basket.pkl'

In [ ]:
import matplotlib.pyplot as plt


# Step 1: Analyze Spend Distribution
print("Spend Statistics:")
print(df['Spend'].describe())

# Plot the distribution of Spend
plt.figure(figsize=(10, 6))
plt.hist(df['Spend'], bins=30, color='blue', alpha=0.7, edgecolor='black')
plt.axvline(df['Spend'].median(), color='red', linestyle='--', label='Median Spend')
plt.axvline(df['Spend'].mean(), color='green', linestyle='--', label='Mean Spend')
plt.title("Spend Distribution")
plt.xlabel("Spend")
plt.ylabel("Frequency")
plt.legend()
plt.show()

# Step 2: Define Threshold Based on Percentile
# For example, select the 25th percentile as the churn threshold
threshold = df['Spend'].quantile(0.25)
print(f"Threshold for Churn (25th Percentile): {threshold}")

In [ ]:
from sklearn.linear_model import LogisticRegression

# Define churn based on engagement (example logic)
df['Churn'] = df['Spend'].apply(lambda x: 1 if x < 1.69 else 0)

X = df[['Spend', 'Units', 'Income_range', 'Hshd_size', 'Children']]
y = df['Churn']

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train the Logistic Regression model
model_churn = LogisticRegression()
model_churn.fit(X_train, y_train)

# Evaluate the model
accuracy = model_churn.score(X_test, y_test)
print("Churn Prediction Accuracy:", accuracy)

# Save the model
joblib.dump(model_churn, "logistic_regression_churn.pkl")

In [ ]:
# Count the number of churned customers (1's in y)
num_churned = y.sum()

print(f"Number of churned customers (y = 1): {num_churned}")

In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
import joblib

# Define churn based on engagement (using threshold Spend < 1.69)
df['Churn'] = df['Spend'].apply(lambda x: 1 if x < 1.69 else 0)

# Feature matrix and target variable
X = df[['Spend', 'Units', 'Income_range', 'Hshd_size', 'Children']]
y = df['Churn']

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train the Logistic Regression model
model_churn = LogisticRegression()
model_churn.fit(X_train, y_train)

# Evaluate the model
y_pred = model_churn.predict(X_test)
print("Classification Report:")
print(classification_report(y_test, y_pred))

# Step 1: Feature Importance
feature_importance = pd.DataFrame({
    'Feature': X.columns,
    'Coefficient': model_churn.coef_[0]
}).sort_values(by='Coefficient', ascending=False)
print("Feature Importance:")
print(feature_importance)

# Step 2: Correlation Heatmap
plt.figure(figsize=(10, 6))
sns.heatmap(df[['Spend', 'Units', 'Income_range', 'Hshd_size', 'Children', 'Churn']].corr(), annot=True, cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()

# Step 3: Bar Plot of Churn Distribution
plt.figure(figsize=(8, 6))
sns.countplot(x='Churn', data=df, palette='Set2')
plt.title("Churn Distribution")
plt.xlabel("Churn (0 = Active, 1 = Churned)")
plt.ylabel("Count")
plt.show()

# Save the model
joblib.dump(model_churn, "enhanced_logistic_regression_churn.pkl")